name: sample-golang-multi-image
services:
- name: edge
  environment_slug: go
  github:
    repo: bojand/sample-golang-multi
    branch: service_docker_image
  envs:
  - key: TARGET_COMPONENT
    value: "intsvc0:3000"
    scope: RUN_TIME
  - key: COMPONENT_NAME
    value: ${_self.PRIVATE_DOMAIN}
    scope: RUN_TIME
- name: intsvc0
  environment_slug: go
  github:
    repo: bojand/sample-golang-multi
    branch: service_docker_image
  internal_ports:
  - 3000
  envs:
  - key: TARGET_COMPONENT
    value: "intsvc1:5678"
    scope: RUN_TIME
  - key: COMPONENT_NAME
    value: ${_self.PRIVATE_DOMAIN}
    scope: RUN_TIME
- name: intsvc1
  image:
    repository: hashicorp/http-echo
    tag: 0.2.3
  internal_ports:
  - 5678
  run_command: "/http-echo -text='hello world'"